name: Build and Deploy to Coolify

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: itsawildsyneon/litterapi:latest

      - name: Trigger Coolify deployment
        run: |
          curl -k -X GET "${{ secrets.COOLIFY_WEBHOOK }}?image_tag=latest" \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"
