name: Build and Deploy to Coolify

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-platform builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io             # of docker.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/niels2804/littertracker-ai:latest

      - name: Trigger Coolify deployment
        run: |
          curl -k -X GET "${{ secrets.COOLIFY_WEBHOOK }}?image_tag=latest" \-H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"

     
